services:
  # HashiCorp Vault
  vault:
    image: hashicorp/vault:latest
    container_name: hashicorp_vault
    ports:
      - "8200:8200"
    volumes:
      - ./vault/vault.hcl:/etc/vault/vault.hcl
      - ./vault/data:/vault/data
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    entrypoint: vault server -config=/etc/vault/vault.hcl
    cap_add:
      - IPC_LOCK                                    # Memory protection from Swapping
    networks:
      - woocommerce_net     # talks to this stack
      - airflow_net
    restart: unless-stopped

  minio:                                            # S3 Storage
    image: minio/minio:latest
    container_name: minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"                                 # S3 API Endpoint
      - "9001:9001"                                 # Web Console MinIo
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD} 
    command: server /data --console-address ":9001"
    networks:
      - woocommerce_net     # talks to this stack
    restart: unless-stopped

  wordpress_db:
    image: mysql:8.0
    container_name: wordpress_db
    volumes: 
      - wp_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${WP_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
    networks:
      - woocommerce_net     # talks to this stack
    restart: unless-stopped

  wordpress:
    depends_on:
      - wordpress_db
    image: wordpress:latest
    container_name: wp_obrf
    ports:
      - "8087:80"
    volumes:
      - wp_core_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
    networks:
      - woocommerce_net     # talks to this stack
    restart: unless-stopped

  staging_db:
    image: postgres:15-alpine
    container_name: staging_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${STAGING_DB_NAME}
      POSTGRES_USER: ${STAGING_DB_USER}
      POSTGRES_PASSWORD: ${STAGING_DB_PASSWORD}
    volumes:
      - pg_staging_data:/var/lib/postgresql/data
    networks:
    - woocommerce_net     # talks to this stack
    - airflow_net         # talks to Airflow too
    restart: unless-stopped

volumes:
  minio_data:
  wp_db_data:
  wp_core_data:
  pg_staging_data:

networks:
  woocommerce_net:
    name: woocommerce_net
  airflow_net:
    external: true
    name: airflow_default
