services:
  # HashiCorp Vault
  vault:
    image: hashicorp/vault:latest
    container_name: hashicorp_vault
    ports:
      - "8200:8200"                                 #API & WEB UI
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID: "root_token_local"
      - VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      - VAULT_ADDR: "http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK                                    # Memory protection from Swapping
    command: server -dev
    restart: unless-stopped

  minio:                                            # S3 Storage
  image: minio/minio:latest
    container_name: minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"                                 # S3 API Endpoint
      - "9001:9001"                                 # Web Console MinIo
    environment:
      MINIO_ROOT_USER: ${MINOI_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD} 
    command:
    restart: unless-stopped

